### ISSUE TITLE
noble not maintained anymore

### ISSUE THREAD

**Issue by nanosonde** [oyooyo/simble#1]
Hi!
According to [this](https://github.com/noble/node-bluetooth-hci-socket/issues/84) thread it seems that noble is not maintained anymore by sandeepmistry.
It is now maintained here: https://github.com/abandonware/noble
Also the required dependencies for the bluetooth-hci-socket.

Would it be ok for you to update you package.json to this new location?
simble and keyble do not build anymore with current nodejs version 10 which is stable and LTS.

**Comment by oyooyo** [comment]
It seems you're right about the original noble currently not being maintained anymore.
I did as you recommended and switched to the abandonware fork.
I just published simble 0.2.5 which uses that fork.
